### PR TITLE
Drafted Code of Conduct

### PR DESCRIPTION
**Pull request by MaksymKarunos**
Drafted Code of Conduct based on best common practices for Open Source projects.

### CODE REVIEW

**Comment by ahnaf-zamil** [comment]
Reviewed your files. Nice job! Grammar is okay, a nice bit of elegance, not too much instructive, I like it.

If you are happy with your commits, can I merge the pr with the master branch? If you need to fix anything, now's your chance. Once you are satisfied, just comment here.

**Comment by StarrMan303** [comment]
Are there any other things that can be added to the ``CODE_OF_CONDUCT.md``? Right now it's really good but there is always a way to make it even better, you know what I mean?

**Comment by ahnaf-zamil** [comment]
> 
> 
> Are there any other things that can be added to the `CODE_OF_CONDUCT.md`? Right now it's really good but there is always a way to make it even better, you know what I mean?

I think it's ok for now. Let's just wait for him to say if he is ready to merge the pr or if he needs to change something

**Comment by MaksymKarunos** [comment]
There are some already made templates for code of conduct, I personally wrote it all myself to underline what I see as most important. The template is like 5 pages long and mine is to the point. 

I think it is ok for now. I will think about what I can add in the future when we grow big. If you think there is something missing let me know. Sorry for my crappy comments 🥇

**Comment by ahnaf-zamil** [comment]
> 
> 
> There are some already made templates for code of conduct, I personally wrote it all myself to underline what I see as most important. The template is like 5 pages long and mine is to the point.
> 
> I think it is ok for now. I will think about what I can add in the future when we grow big. If you think there is something missing let me know. Sorry for my crappy comments 🥇

Not a crappy comment man. So I guess I can merge the pr. Thanks

**Pull request merged**
